### ISSUE TITLE
View image from camera through RPi

### ISSUE THREAD

**Issue by emeurrens** [emeurrens/parking-availability-system#11]
Write code to interface with RPi camera module using camera libraries on the system already (see [documentation](https://www.raspberrypi.com/documentation/computers/camera_software.html))

Acceptance Criteria:
- Able to capture an single image frame from the camera that can be viewed in either Jupyter Notebook or from the file system using a valid file format
- Optional, but better yet, be able to view a live video feed from the camera

**Comment by tobonev** [comment]
Single JPG image has been captured and stored on the local host file system.
