### ISSUE TITLE
Establish connection from from RPi to AWS and SQL database

### ISSUE THREAD

**Issue by emeurrens** [emeurrens/parking-availability-system#9]
- Install a database server for the RPi (not sure if this is fully necessary but a client is)
- Determine SQL library to be installed with Python, will depend on the SQL version we use to determine the client connection protocol
- Connect to SQL database and just test if the RPi can read/write values

Acceptance criteria:
- Pi is able to read and write values to SQL database

**Comment by bsimonson1** [comment]
- RPi is able to connect to a PostgreSQL database. 
- RPi is able to read and write values to the database.
